language: java
jdk:
  - oraclejdk8
sudo: false
install: true
script: cd "SGA_Build" && mvn -e clean install

before_deploy:
  - cd ..
  - pwd && ls -l
  - mkdir -p "dpl_cd_upload"
  - mv "SGA_Apex_REST_API_WAR/target/SGA_Apex_REST_API_WAR-0.1.0.war" "dpl_cd_upload/SGA_Apex_REST_API_WAR-0.1.0.war"
  - pwd && ls -l

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    bucket: airavata-team-apex
    region: us-west-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on: &2
      repo: airavata-courses/TeamApex
      all_branches: true
notifications:
  email:
    recipients:
      - erika27desouza@gmail.com
      - vaglomangirish@gmail.com
      - shenoy.200@gmail.com
