language: java
jdk:
  - oraclejdk8
sudo: false
install: true
script: cd "SGA_Build" && mvn -e clean install
notifications:
  email:
    recipients:
      - erika27desouza@gmail.com
      - vaglomangirish@gmail.com
      - shenoy.200@gmail.com
